export const commentsSection7 = [
  {
    id: "23OZ1poIcLyfAa4Oz4fY",
    userId: "ian_84@gmail.com",
    content: "How long did it take you to make it???",
    tag: "questions",
    timestamp: {
      seconds: 1733201263,
      nanoseconds: 481000000,
    },
    clap: 31,
    clappedBy: [],
    replies: [
      {
        id: "mywsjbm22ZL7Xf79UGWd",
        parentId: "23OZ1poIcLyfAa4Oz4fY",
        userId: "Vx7qldr9JUSrZ22I3lIb83mm8vu1",
        parentUserId: "ian_84@gmail.com",
        content: "Mins?",
        tag: "questions",
        timestamp: {
          seconds: 1733201264,
          nanoseconds: 213000000,
        },
        clap: 30,
        clappedBy: [],
      },
      {
        id: "PfZbFDYAM4VXYEG3DLT6",
        parentId: "23OZ1poIcLyfAa4Oz4fY",
        userId: "Vx7qldr9JUSrZ22I3lIb83mm8vu1",
        parentUserId: "ian_84@gmail.com",
        content: "like around 15-20??✨",
        tag: "questions",
        timestamp: {
          seconds: 1733201263,
          nanoseconds: 846000000,
        },
        clap: 9,
        clappedBy: [],
      },
    ],
  },
  {
    id: "4HlXvdC0UsFmk5oxz16s",
    userId: "nora_b@gmail.com",
    content: "made it but my yarn was huge made it look chunkyy😭😭",
    tag: "others",
    timestamp: {
      seconds: 1733201257,
      nanoseconds: 811000000,
    },
    clap: 12,
    clappedBy: [],
    replies: [],
  },
  {
    id: "InJtEkT07PmbYV1ffMhK",
    userId: "cole_j@gmail.com",
    content:
      "little question, can we make this with circular needles as well ??",
    tag: "questions",
    timestamp: {
      seconds: 1733201272,
      nanoseconds: 989000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "JcOwGJKo1ZW0msoG2cZH",
    userId: "jack88@gmail.com",
    content:
      "BAHAHHAHA THANK U I MADE IT WITH LOOP YARN AND IT TURNED SO BIGG THAKK UU LOL😂😂",
    tag: "others",
    timestamp: {
      seconds: 1733201248,
      nanoseconds: 216000000,
    },
    clap: 9,
    clappedBy: [],
    replies: [],
  },
  {
    id: "MDeb2PVMGTzP08mB9qkG",
    userId: "DzBmpq9eg4gDIpo3CV0S96KPTOS2",
    content:
      "This was my first official crochet project and it was so fun! Now I want to make one for everyone I know 😂",
    tag: "",
    timestamp: {
      seconds: 1733482948,
      nanoseconds: 254000000,
    },
    clap: 13,
    clappedBy: [],
    replies: [],
  },
  {
    id: "QwUAB7amPuAbAc5QLDom",
    userId: "mike_d@gmail.com",
    content: "omg tysmmmm! also what headphones are those? they are so cute!!",
    tag: "questions",
    timestamp: {
      seconds: 1733201247,
      nanoseconds: 463000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "SxojHM4X2Qz5D55a5K7P",
    userId: "eric_t@gmail.com",
    content: "Thank you so much! Also how do you price your items?",
    tag: "questions",
    timestamp: {
      seconds: 1733201261,
      nanoseconds: 465000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "dFPb0E6PDkAA2WwZFIyl",
    userId: "emma_l@gmail.com",
    content:
      "Omg your headphones are so pretty could you tell me which headphones you have? I tried to search them up online but couldnt find them 😅 (which brand is it from?)",
    tag: "questions",
    timestamp: {
      seconds: 1733201248,
      nanoseconds: 620000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "i3EIew3pDqre8oLw4SdT",
    userId: "nina_p@gmail.com",
    content:
      "Thank you for sharing this! I made this as a charm for a popcorn bag I made for my friend, and the bag is yellow so it ended up looking like a lemon bag! 🍋",
    tag: "others",
    timestamp: {
      seconds: 1733201239,
      nanoseconds: 346000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "lgaoPvJXwVOBLhse8yia",
    userId: "DzBmpq9eg4gDIpo3CV0S96KPTOS2",
    content: "🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱",
    tag: "",
    timestamp: {
      seconds: 1733482987,
      nanoseconds: 843000000,
    },
    clap: 13,
    clappedBy: [],
    replies: [],
  },
  {
    id: "rZvsIz5MhDYSzeCiOQfj",
    userId: "ben_h@gmail.com",
    content:
      "🌱 Just used your tutorial, my sprout unfortunately came out quite bulky and uneven, but I suspect I used too thick of a yarn- 😅 Might be the biggest sprout ever, but it's mine, I made it, it did not exist and now it does, so I'm proud, and thank you for such a damn fine tutorial, you have a knack for it ❤",
    tag: "mistakes",
    timestamp: {
      seconds: 1733201251,
      nanoseconds: 280000000,
    },
    clap: 2,
    clappedBy: ["aagNYe4N79XCMVaA3Vb3nmloeZh1", "jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [],
  },
  {
    id: "vhjTkPu6m5iL9PHYJFEp",
    userId: "nick_j@gmail.com",
    content: "Next time can you do a headband crochet tutorial?",
    tag: "questions",
    timestamp: {
      seconds: 1733201252,
      nanoseconds: 407000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
];
