export const commentsSection4 = [
  {
    id: "0949bJ4fL3JXEY68weDz",
    userId: "rosa_m@gmail.com",
    content: "My first 10 chains were way looser than yours does that matter?",
    tag: "questions",
    timestamp: {
      seconds: 1733201263,
      nanoseconds: 117000000,
    },
    clap: 13,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [
      {
        id: "Pp1kyy3xVjturjrmzA2R",
        parentId: "0949bJ4fL3JXEY68weDz",
        userId: "YFgcb54LcTeBOaNnJNaOXOFvSiW2",
        parentUserId: "rosa_m@gmail.com",
        content: "you can tighten it^^",
        tag: "",
        timestamp: {
          seconds: 1733225002,
          nanoseconds: 389000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "7Sx0SZkJFPe5rcNMxFWK",
    userId: "iris_k@gmail.com",
    content:
      "Question: when I look in the book of the different stitches, such as single crochet, double crochet, half crochet and treble crochet, I noticed that in the book the way that it says the technical of yoing , the books are showing it differently than how you’re demonstrating yoing. So when I actually follow the written pattern, I noticed what you’re demonstrating does not go by the exact technical way of completing the different crochet threading.\nI am using an English crochet book and definitions",
    tag: "questions",
    timestamp: {
      seconds: 1733201272,
      nanoseconds: 228000000,
    },
    clap: 15,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [
      {
        id: "ltGEjVuxv1Mv2TVRUucW",
        parentId: "7Sx0SZkJFPe5rcNMxFWK",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "iris_k@gmail.com",
        content:
          "because im using US terminology and youre probably using UK terminology🤔",
        tag: "questions",
        timestamp: {
          seconds: 1733201272,
          nanoseconds: 600000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "7nm1PzN6clt2lDhocsXr",
    userId: "rex_h@gmail.com",
    content:
      "if i have smaller yarn, should i just do the same and then have a smaller version or can I do double the things you say? so when you chain 10 I should then chain 20 and when you do 1 dc i do 2? or does that not work?\ni dont have any thick yarn 😭",
    tag: "questions",
    timestamp: {
      seconds: 1733201295,
      nanoseconds: 470000000,
    },
    clap: 12,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "8bIz2C0BnnzG3JuL7uQr",
    userId: "mae_87@gmail.com",
    content:
      "im confused, why are we starting the other side from the first chain and not the second chain like we did when we started?",
    tag: "questions",
    timestamp: {
      seconds: 1733201277,
      nanoseconds: 145000000,
    },
    clap: 12,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [
      {
        id: "7Vx1hktXEruRVtlgD7wZ",
        parentId: "8bIz2C0BnnzG3JuL7uQr",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "mae_87@gmail.com",
        content: " @Mae of course !",
        tag: "questions",
        timestamp: {
          seconds: 1733201278,
          nanoseconds: 771000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "guYaeSc4c9Uk2IEyyThD",
        parentId: "8bIz2C0BnnzG3JuL7uQr",
        userId: "mae_87@gmail.com",
        parentUserId: "mae_87@gmail.com",
        content: "okay tysm! @Mandi",
        tag: "questions",
        timestamp: {
          seconds: 1733201278,
          nanoseconds: 333000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "8kGIePGXmRuX67aZUAdi",
        parentId: "8bIz2C0BnnzG3JuL7uQr",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "mae_87@gmail.com",
        content:
          "Also, by skipping one you technically only have 9 chains left on the other side , so if you would skip another one you would run out of chains",
        tag: "questions",
        timestamp: {
          seconds: 1733201277,
          nanoseconds: 951000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "lNatevpHph1FLpJ6eOfC",
        parentId: "8bIz2C0BnnzG3JuL7uQr",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "mae_87@gmail.com",
        content:
          "Bc in the first one , you would basically undo what you just did, but the second time its already secured. Hope that helps <3",
        tag: "questions",
        timestamp: {
          seconds: 1733201277,
          nanoseconds: 508000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "EkJQwBgQqtfZg72fSiPi",
    userId: "maya_h@gmail.com",
    content: "Why does mine look like a deformed duck in the 1st leaf",
    tag: "questions",
    timestamp: {
      seconds: 1733201261,
      nanoseconds: 55000000,
    },
    clap: 3,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "Fxcxb7klfNsLb98gPL6W",
    userId: "DzBmpq9eg4gDIpo3CV0S96KPTOS2",
    content: "Me: Repeating this step 10times..😭😭",
    tag: "",
    timestamp: {
      seconds: 1733482881,
      nanoseconds: 855000000,
    },
    clap: 10,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "Fyuq4PxOrZpsvmdCWchK",
    userId: "chad_m@gmail.com",
    content: "I dont understand how you hide the first leaf yarn 😢",
    tag: "questions",
    timestamp: {
      seconds: 1733201276,
      nanoseconds: 5000000,
    },
    clap: 21,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "HPHNHoiL1TmGQbtisMna",
    userId: "dev123@gmail.com",
    content:
      "Hi! I am completely a beginner at crochet. Can you show me where the next chain is? im so confused where to put my hook or where the next chain is😅",
    tag: "questions",
    timestamp: {
      seconds: 1733201238,
      nanoseconds: 836000000,
    },
    clap: 4,
    clappedBy: [],
    replies: [],
  },
  {
    id: "KG38cPIkJLoRuZVEy0yh",
    userId: "dean_k@gmail.com",
    content:
      "Hi\nFor the leaf, after chain 10, sl in 2nd ch from the hook.\nBut in the video isnt it the 1st ch from the hook? So the yarn on the hook also counted as 1 ch? I am a bit confused",
    tag: "questions",
    timestamp: {
      seconds: 1733201260,
      nanoseconds: 546000000,
    },
    clap: 9,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "RtvhHw590SZ1cr0KOnrQ",
    userId: "vera_j@gmail.com",
    content:
      "when you go back to do the other half of the leaf do you stick the needle inside the v (stitch) ir loop the whole v on your needle?\nlove the video super informative and helpful but for some reason mine doesn't come out like yours!!",
    tag: "questions",
    timestamp: {
      seconds: 1733201294,
      nanoseconds: 743000000,
    },
    clap: 43,
    clappedBy: [],
    replies: [
      {
        id: "SUdgiYwf6uq5RiFkbHtY",
        parentId: "RtvhHw590SZ1cr0KOnrQ",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "vera_j@gmail.com",
        content:
          "u mean when ur weaving in? i just stick my needle into the loops on the back of the leaf where no one can see from the front~",
        tag: "questions",
        timestamp: {
          seconds: 1733201295,
          nanoseconds: 106000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "YOdQ1HV0nNLUGM4rWDQP",
    userId: "mia_90@gmail.com",
    content: "12:42 wait how come she has two loops now 😭😭",
    tag: "questions",
    timestamp: {
      seconds: 1733201250,
      nanoseconds: 145000000,
    },
    clap: 5,
    clappedBy: ["jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [],
  },
  {
    id: "YljL4SOpkbTvQi89p2Vx",
    userId: "TdsTJxteN2T2lQUSbGGpj14TTfg2",
    content:
      "I think my yarn is a bit thicker for the needle  that I have. It is better to use thin yarn with a steel needle. ",
    tag: "",
    timestamp: {
      seconds: 1733462947,
      nanoseconds: 36000000,
    },
    clap: 3,
    clappedBy: ["jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [],
  },
  {
    id: "ZbssgqSKcNNh0qPWMcSB",
    userId: "rita_s@gmail.com",
    content:
      "Wait wait wait!! I've been trying to give time to crocheting but I cant cuz of my exams but here's my real question: Does it really matter if we yarn Over instead in yarning Under ? (Edit): And if yes what changes?",
    tag: "questions",
    timestamp: {
      seconds: 1733201260,
      nanoseconds: 37000000,
    },
    clap: 12,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2"],
    replies: [],
  },
  {
    id: "fLNh8wbz9ZhtUy6Qfm1c",
    userId: "neil_s@gmail.com",
    content:
      "I tried to make the leaf but it ended up in a straight line :( Idk how urs worked",
    tag: "mistakes",
    timestamp: {
      seconds: 1733201283,
      nanoseconds: 174000000,
    },
    clap: 2,
    clappedBy: ["DzBmpq9eg4gDIpo3CV0S96KPTOS2", "jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [
      {
        id: "qvhPqWeWAaO9XTnxOv4M",
        parentId: "fLNh8wbz9ZhtUy6Qfm1c",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "neil_s@gmail.com",
        content: "Samee",
        tag: "mistakes",
        timestamp: {
          seconds: 1733201283,
          nanoseconds: 570000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "fVZJJnmesUjHTjv8QeAH",
    userId: "ray_82@gmail.com",
    content:
      "Chain 10\nSlipknot into the second chain from the hook\nSingle crochet (1)\nHalf double crochet(1)\nDouble crochet (1)\nTreble crochet increase (2 in the same stitch)\nDouble crochet (1)\nHalf double crochet (1)\nSingle crochet (1)\nSlip-stich \nSlip stitch into the first stich of the other side of the leaf\nNow repeat the above steps for the other side as well\nOnce you reach the top of the leaf than you chain 10 again and repeat this entire process again\nAfter the second leaf is done than you cut the yarn and weave it in\nStick the hook between both leaves \nNow make a slip knot with the yarn and join it in the middle of the leaf \nMake as many chains as you want \nFold the chain in half now and connect it with the first stich of the chain through a slip stich \n \nI'm sorry if this wasn't the best pattern though",
    tag: "tips",
    timestamp: {
      seconds: 1733201286,
      nanoseconds: 885000000,
    },
    clap: 4,
    clappedBy: [],
    replies: [
      {
        id: "UngFfGK1R5vnluMN099d",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "Thank you so much better",
        tag: "tips",
        timestamp: {
          seconds: 1733201291,
          nanoseconds: 878000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "sP7ZtJzWE1y5GgJBHC5A",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "thank you very much this was very helpfull !!",
        tag: "tips",
        timestamp: {
          seconds: 1733201291,
          nanoseconds: 480000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "Sq5HOHbewcr0KWTTIcMH",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content:
          " @lauren9659  i think it's called both I'm sorry for the confusion tho 😭",
        tag: "tips",
        timestamp: {
          seconds: 1733201291,
          nanoseconds: 115000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "SkBDFXqfCyzMRcU7oXnt",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "Slipknot into chain?? You mean slip stitch",
        tag: "tips",
        timestamp: {
          seconds: 1733201290,
          nanoseconds: 751000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "NjfriRDkiCyciHlhVDwB",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "Ilyy",
        tag: "tips",
        timestamp: {
          seconds: 1733201290,
          nanoseconds: 342000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "b0cFEbh0PbyTtkxm6gMb",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content:
          "​@woof-barkbark  that's I guess why she had the insta one too. But I'm the same way😂",
        tag: "tips",
        timestamp: {
          seconds: 1733201289,
          nanoseconds: 884000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "WmP41AhospWskHsU4qeR",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content:
          "Mt dumb ass is hurting from sitring and i almost cant type omg my hands hurt iam litterally chaking",
        tag: "tips",
        timestamp: {
          seconds: 1733201289,
          nanoseconds: 522000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "hyw9v2QCfX29WsPUWlT2",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "you are the best",
        tag: "tips",
        timestamp: {
          seconds: 1733201289,
          nanoseconds: 91000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "i1Gfi1JtCclRYY3Ozvj5",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "TYSMMMM",
        tag: "tips",
        timestamp: {
          seconds: 1733201288,
          nanoseconds: 728000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "atJDdEe0LfEkHl7sOjc7",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content:
          "Ty so much 😭 I'm not a beginner and I have adhd so the slow pace and explanations kept making me zone out",
        tag: "tips",
        timestamp: {
          seconds: 1733201288,
          nanoseconds: 355000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "OPBYdf2pXYnjSgtR1Xld",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "ily",
        tag: "tips",
        timestamp: {
          seconds: 1733201287,
          nanoseconds: 989000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "QUkJbpxsggQdrJLuTmxH",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "thank you queen. Very helpful",
        tag: "tips",
        timestamp: {
          seconds: 1733201287,
          nanoseconds: 612000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "7hX5PuTz2prvgA3WEBfJ",
        parentId: "fVZJJnmesUjHTjv8QeAH",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "ray_82@gmail.com",
        content: "Tysm you helped me ❤",
        tag: "tips",
        timestamp: {
          seconds: 1733201287,
          nanoseconds: 254000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "gkzwSapiZZLjmhMMG7lo",
    userId: "mark_v@gmail.com",
    content:
      "I messed up, my fingers are sobbing at this point. When i was satrting to grow my stictch, my yarn's threads kept getting stuck, and the threads separated😃",
    tag: "mistakes",
    timestamp: {
      seconds: 1733201258,
      nanoseconds: 929000000,
    },
    clap: 21,
    clappedBy: ["IRVD2f2xkrVNoVnFKGjG7uvLwtW2", "jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [
      {
        id: "84HCQpAyQGrBvZvOaR2F",
        parentId: "gkzwSapiZZLjmhMMG7lo",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "mark_v@gmail.com",
        content:
          "It sounds like your yarn might be splitting, which can happen with some types of yarn. Try switching to a smoother, tightly spun yarn that doesn't fray.",
        tag: "",
        timestamp: {
          seconds: 1733222463,
          nanoseconds: 163000000,
        },
        clap: 4,
        clappedBy: [],
        isPinned: true,
      },
    ],
  },
  {
    id: "oB26FDsl9k4rdgRfQt14",
    userId: "adam_p@gmail.com",
    content:
      "shouldnt be 9 chains since the inc is in the same chain as the previous one ?",
    tag: "questions",
    timestamp: {
      seconds: 1733201266,
      nanoseconds: 95000000,
    },
    clap: 42,
    clappedBy: [],
    replies: [
      {
        id: "koo1xPWRTChDWqXdbmW3",
        parentId: "oB26FDsl9k4rdgRfQt14",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "adam_p@gmail.com",
        content:
          "the slip stitch is placed in the second chain from hook💗 so its 10 ch in total~",
        tag: "questions",
        timestamp: {
          seconds: 1733201266,
          nanoseconds: 477000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "rh3QMYp8nCOgQG4g6g10",
    userId: "lucy_r@gmail.com",
    content:
      "What to do with the tail end,  I didn’t add it in btwn cos I didn’t understand how to properly...😅yea so, what should I do with the tail end, cut it?",
    tag: "questions",
    timestamp: {
      seconds: 1733201251,
      nanoseconds: 643000000,
    },
    clap: 43,
    clappedBy: [],
    replies: [
      {
        id: "D4KU3TAz8OU3J6f2CJmx",
        parentId: "rh3QMYp8nCOgQG4g6g10",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "lucy_r@gmail.com",
        content: "i dont undertand either",
        tag: "questions",
        timestamp: {
          seconds: 1733201252,
          nanoseconds: 19000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "tBdmiZnNOgc9vagqX0Ti",
    userId: "jane_w@gmail.com",
    content: "10:20 she got a triangle why is mine a T",
    tag: "questions",
    timestamp: {
      seconds: 1733201255,
      nanoseconds: 426000000,
    },
    clap: 14,
    clappedBy: [],
    replies: [
      {
        id: "D5u53JEpM7uwR4OUmaQf",
        parentId: "tBdmiZnNOgc9vagqX0Ti",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "jane_w@gmail.com",
        content: "You gotta trust the process that is only HALF of the leaf",
        tag: "questions",
        timestamp: {
          seconds: 1733201255,
          nanoseconds: 815000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "u7O6WojmFQWfjCOdAqwD",
    userId: "tina_s@gmail.com",
    content:
      'Here’s a little written version for everyone!❤\nI know it’s on your instagram but some people don’t have it \n\n1ST LEAF\n\nch10, sl in 2nd ch from hook, sc, hdc, dc, 2tc in 1st, dc, hdc, sc, sl\n\nturn your work and work on your piece from the base sl, sc, hdc, dc, 2tc in 1st, dc, hdc, sc, sl\n\n2ND LEAF\n\nch10, sl in 2nd ch from hook, sc, hdc, dc, 2tc in 1st, dc, hdc, sc, sl\n\n"turn your work and work on your piece from the base* sl, sc, hdc, dc, 2tc in 1st, dc, hdc, sc, sl, fo\n\nSTEM\n\nsl in between 2 leaves, ch40-60 depending on your headphone, sl in between 2 leaves, fo\n\nweave in\n\n\nHope yall enjoyed!',
    tag: "tips",
    timestamp: {
      seconds: 1733201250,
      nanoseconds: 891000000,
    },
    clap: 4,
    clappedBy: [],
    replies: [],
  },
  {
    id: "wcKAxBfZIkJvCdZoZA4B",
    userId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
    content: "This is a nice tutorial!",
    tag: "",
    timestamp: {
      seconds: 1733832597,
      nanoseconds: 575000000,
    },
    clap: 14,
    clappedBy: [],
    replies: [
      {
        id: "AhbAazSR7OwjEcJf81Xg",
        parentId: "wcKAxBfZIkJvCdZoZA4B",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
        content: "I really have to agree~~",
        tag: "",
        timestamp: {
          seconds: 1733832624,
          nanoseconds: 482000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "wcu0Uj93kmQkeipvt2aR",
    userId: "sean_t@gmail.com",
    content:
      "Hi, this tutorial is very good, but I was wondering how can I make a bigger one? what should I change?",
    tag: "questions",
    timestamp: {
      seconds: 1733201280,
      nanoseconds: 722000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [
      {
        id: "OcUYWLTrw1EvUKlnaXob",
        parentId: "wcu0Uj93kmQkeipvt2aR",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "sean_t@gmail.com",
        content: " @lilthings.  thank you very much!❤",
        tag: "questions",
        timestamp: {
          seconds: 1733201281,
          nanoseconds: 503000000,
        },
        clap: 4,
        clappedBy: [],
      },
      {
        id: "2YNzcY5VhWDBeXmOX237",
        parentId: "wcu0Uj93kmQkeipvt2aR",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "sean_t@gmail.com",
        content:
          "u can use a bigger yarn with the corrisponding hook size! for example a chunky yarn with a 6mm hook size",
        tag: "questions",
        timestamp: {
          seconds: 1733201281,
          nanoseconds: 126000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "xAkowBKaVKTSAJTsprWI",
    userId: "raja_v@gmail.com",
    content: "My leaf looks possessed",
    tag: "others",
    timestamp: {
      seconds: 1733201245,
      nanoseconds: 884000000,
    },
    clap: 24,
    clappedBy: [],
    replies: [
      {
        id: "UV4dtOqiGK0mD50zO95c",
        parentId: "xAkowBKaVKTSAJTsprWI",
        userId: "PgRRruOoU2VsTNvhF6j05iTTOfe2",
        parentUserId: "raja_v@gmail.com",
        content:
          "OH NOOO DO U WANNA SD ME A DM OF A PHOTO?? maybe i could help😅",
        tag: "others",
        timestamp: {
          seconds: 1733201246,
          nanoseconds: 311000000,
        },
        clap: 4,
        clappedBy: [],
      },
    ],
  },
  {
    id: "xHa1H2Zw3itUnmuBmizp",
    userId: "ruby_k@gmail.com",
    content:
      "I was saurr happy when I completed my first leaf just to realise that i had naur more wool cuz i just started with some random green wool ;then i tried with some yellow wool ??(guys RIP 🪦 that leaf)",
    tag: "others",
    timestamp: {
      seconds: 1733201253,
      nanoseconds: 607000000,
    },
    clap: 4,
    clappedBy: [],
    replies: [],
  },
  {
    id: "zBtMHwtvC1HnOUFtnMv5",
    userId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
    content:
      "My stitches are so tight, I can’t get the needle through the knots ",
    tag: "mistakes",
    timestamp: {
      seconds: 1733221914,
      nanoseconds: 267000000,
    },
    clap: 30,
    clappedBy: ["aagNYe4N79XCMVaA3Vb3nmloeZh1", "jm8nVXBzC1OVCZaQgsnF4WrMfSX2"],
    replies: [
      {
        id: "ehTr4kvhumaRS7MxUeuo",
        parentId: "zBtMHwtvC1HnOUFtnMv5",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
        content:
          "Try working your stitches a bit looser, especially at the beginning—it’ll make it much easier to insert the needle :)",
        tag: "",
        timestamp: {
          seconds: 1733222421,
          nanoseconds: 912000000,
        },
        clap: 19,
        clappedBy: [],
        isPinned: true,
      },
    ],
  },
];
