export const commentsSection2 = [
  {
    id: "0dL42QHeLwWfcL6sbHbP",
    userId: "gia_p@gmail.com",
    content: "sorry, may I know what material you use for the thread?",
    tag: "questions",
    timestamp: {
      seconds: 1733201279,
      nanoseconds: 590000000,
    },
    clap: 13,
    clappedBy: [],
    replies: [
      {
        id: "p0LDncqk7UMoLqyHGjaI",
        parentId: "0dL42QHeLwWfcL6sbHbP",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "gia_p@gmail.com",
        content: "thx ^^ <3 @lilthings. ",
        tag: "questions",
        timestamp: {
          seconds: 1733201280,
          nanoseconds: 356000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "5bP3vUlXvkTW1qnWqSP8",
        parentId: "0dL42QHeLwWfcL6sbHbP",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "gia_p@gmail.com",
        content: "milk cotton yarn~",
        tag: "questions",
        timestamp: {
          seconds: 1733201279,
          nanoseconds: 960000000,
        },
        clap: 10,
        clappedBy: [],
      },
    ],
  },
  {
    id: "14vHaxIoSc9CJ1PbcHSj",
    userId: "jay_k@gmail.com",
    content:
      "I somehow have two 2,5mm and two 3,5mm but not a single 3mm how?? 🥲",
    tag: "others",
    timestamp: {
      seconds: 1733201240,
      nanoseconds: 373000000,
    },
    clap: 91,
    clappedBy: [],
    replies: [
      {
        id: "swaruHBRYhscb0EF6hwV",
        parentId: "14vHaxIoSc9CJ1PbcHSj",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "jay_k@gmail.com",
        content: "ohh its ok u could use 3.5 mm but maybe with 8 ply yarn~~",
        tag: "others",
        timestamp: {
          seconds: 1733201240,
          nanoseconds: 781000000,
        },
        clap: 8,
        clappedBy: [],
      },
    ],
  },
  {
    id: "4LhHMDaq76s92bm9pyzB",
    userId: "brad_k@gmail.com",
    content: "Can I use 3.5mm hook?",
    tag: "questions",
    timestamp: {
      seconds: 1733201267,
      nanoseconds: 235000000,
    },
    clap: 5,
    clappedBy: [],
    replies: [],
  },
  {
    id: "59mDWFWxwQx0eIntJon6",
    userId: "dan_m@gmail.com",
    content: 'Me using plush yarn and a plastic hook "yah I\'ll try :D"',
    tag: "others",
    timestamp: {
      seconds: 1733201253,
      nanoseconds: 219000000,
    },
    clap: 15,
    clappedBy: [],
    replies: [],
  },
  {
    id: "5Gg5SJXjZmY3e6N8DdLv",
    userId: "deb_h@gmail.com",
    content: "Can we use 2.5 mm hook for this?",
    tag: "questions",
    timestamp: {
      seconds: 1733201286,
      nanoseconds: 512000000,
    },
    clap: 20,
    clappedBy: [],
    replies: [],
  },
  {
    id: "6NCc3POwfSAQe6N3NNRy",
    userId: "DzBmpq9eg4gDIpo3CV0S96KPTOS2",
    content: "🌱🌱",
    tag: "",
    timestamp: {
      seconds: 1733482788,
      nanoseconds: 241000000,
    },
    clap: 20,
    clappedBy: [],
    replies: [],
  },
  {
    id: "8lYuC1CO8PPVWvCQMUHT",
    userId: "tara_p@gmail.com",
    content: "I only have a 6.5 mm",
    tag: "others",
    timestamp: {
      seconds: 1733201259,
      nanoseconds: 291000000,
    },
    clap: 10,
    clappedBy: [],
    replies: [],
  },
  {
    id: "91auM3wmVKnL9k92Hb0S",
    userId: "joel_t@gmail.com",
    content: "Can we use a little bigger yarn for this?",
    tag: "questions",
    timestamp: {
      seconds: 1733201284,
      nanoseconds: 298000000,
    },
    clap: 5,
    clappedBy: [],
    replies: [],
  },
  {
    id: "EepJ56zRkcUNFGvUK1fK",
    userId: "ella_m@gmail.com",
    content:
      "I don’t have any green yarn, but I do have a cool looking shade of brown and a pair of white and grey headphones, would it look weird or would it not matter?",
    tag: "questions",
    timestamp: {
      seconds: 1733201266,
      nanoseconds: 863000000,
    },
    clap: 4,
    clappedBy: [],
    replies: [],
  },
  {
    id: "KXnF4PAA3yLSrEt4GcH8",
    userId: "rick_j@gmail.com",
    content:
      "hii just wondering what is the diameter of the yarn you are using?",
    tag: "questions",
    timestamp: {
      seconds: 1733201279,
      nanoseconds: 148000000,
    },
    clap: 21,
    clappedBy: [],
    replies: [],
  },
  {
    id: "MwrI5DZlHt4PEXs7TTgG",
    userId: "tony_m@gmail.com",
    content: "I have 4 ply yarn 😓 would this also work with my yarn?",
    tag: "questions",
    timestamp: {
      seconds: 1733201271,
      nanoseconds: 498000000,
    },
    clap: 21,
    clappedBy: [],
    replies: [
      {
        id: "JSfjUb4sKxeWtIUK801Q",
        parentId: "MwrI5DZlHt4PEXs7TTgG",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "tony_m@gmail.com",
        content: "that would work too!! but maybe use a smaller hook size~~",
        tag: "questions",
        timestamp: {
          seconds: 1733201271,
          nanoseconds: 867000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "Pz4bBF2TR1vFKXspsuch",
    userId: "alma_k@gmail.com",
    content: "what brand of yarn do you use?",
    tag: "questions",
    timestamp: {
      seconds: 1733201281,
      nanoseconds: 942000000,
    },
    clap: 12,
    clappedBy: [],
    replies: [],
  },
  {
    id: "Q8LqoVo1sdJ9qssjNToe",
    userId: "joy_89@gmail.com",
    content:
      "One question, would this work for yarn that needs a 9mm hook? im a beginner and didnt really think what size to buy, 😅 so i grabbed the first one I saw that wasnt too intimidating",
    tag: "questions",
    timestamp: {
      seconds: 1733201267,
      nanoseconds: 684000000,
    },
    clap: 31,
    clappedBy: [],
    replies: [
      {
        id: "FY8KeGmo7rAMPI01dojk",
        parentId: "Q8LqoVo1sdJ9qssjNToe",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "joy_89@gmail.com",
        content: "Yes definitely!1 as long as you use the suitable yarn size",
        tag: "questions",
        timestamp: {
          seconds: 1733201268,
          nanoseconds: 119000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "SSvRkF7bzMHMA5qlII0T",
    userId: "eve_k@gmail.com",
    content:
      "Hi can you tell me what kind of yarn you're using?😭 it looks more neat than mine.",
    tag: "questions",
    timestamp: {
      seconds: 1733201276,
      nanoseconds: 414000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "Tjqr9lkLwjakFjar6YGd",
    userId: "zara_h@gmail.com",
    content: "Can i use a 5.5 mm hook?",
    tag: "questions",
    timestamp: {
      seconds: 1733201265,
      nanoseconds: 725000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "UTHdercXX5OPNjmRJrNp",
    userId: "josh_d@gmail.com",
    content: "Is there someone that can tell me how much the width is in mm???",
    tag: "questions",
    timestamp: {
      seconds: 1733201250,
      nanoseconds: 508000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "V7cpkat2u7Nf1Sl3OzRX",
    userId: "pete_s@gmail.com",
    content: "if i used 4mm yarn what crochet hook do i use",
    tag: "questions",
    timestamp: {
      seconds: 1733201253,
      nanoseconds: 971000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "Vc8L0UQHZKnwvebst7lY",
    userId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
    content:
      "My yarn is thinner than yours and I can’t see the knots,, also it’s super slippery :( ",
    tag: "mistakes",
    timestamp: {
      seconds: 1733222272,
      nanoseconds: 745000000,
    },
    clap: 43,
    clappedBy: ["aagNYe4N79XCMVaA3Vb3nmloeZh1", "IRVD2f2xkrVNoVnFKGjG7uvLwtW2"],
    replies: [
      {
        id: "4nPP4hQY8meg1JfB9FkK",
        parentId: "Vc8L0UQHZKnwvebst7lY",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
        content:
          "Too thin or fluffy yarn is not recommended for beginners. For more manageable projects, you can try using a thicker, smoother yarn.",
        tag: "",
        timestamp: {
          seconds: 1733222325,
          nanoseconds: 321000000,
        },
        clap: 13,
        clappedBy: [],
        isPinned: true,
      },
    ],
  },
  {
    id: "VtLD9aQ7moGLlREYYB2C",
    userId: "sara_t@gmail.com",
    content: "Which type of yarn it is? \nPls answer my question.",
    tag: "questions",
    timestamp: {
      seconds: 1733201247,
      nanoseconds: 851000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "ZJMG477riGnFGJczXTYI",
    userId: "dora_l@gmail.com",
    content:
      "Hii just a question \nDoes anyone have any idea how much yarn this needs? I have a little less than a skein and was wondering if it would be enough ?",
    tag: "questions",
    timestamp: {
      seconds: 1733201268,
      nanoseconds: 890000000,
    },
    clap: 56,
    clappedBy: [],
    replies: [
      {
        id: "WFOaPnAZmP4Rrflxm6XP",
        parentId: "ZJMG477riGnFGJczXTYI",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "dora_l@gmail.com",
        content: " @lilthings.  Tysmmmm🫶🖤✨",
        tag: "questions",
        timestamp: {
          seconds: 1733201269,
          nanoseconds: 717000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "pmDrPL2i72ghpxWI01SJ",
        parentId: "ZJMG477riGnFGJczXTYI",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "dora_l@gmail.com",
        content:
          "i dont know the exact amount but if u have 1/3 of ur yarn skein that shld be fine 💗",
        tag: "questions",
        timestamp: {
          seconds: 1733201269,
          nanoseconds: 350000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "ZUfzegh1aZMuIGAQ87Uc",
    userId: "ivy_p@gmail.com",
    content: "I don't have a darning needle",
    tag: "others",
    timestamp: {
      seconds: 1733201252,
      nanoseconds: 795000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "ZlMJTfGZxuvzaDa9gENR",
    userId: "luke_j@gmail.com",
    content:
      "Would this work if I only have 2 fine yarn? and what size hook would I use?",
    tag: "questions",
    timestamp: {
      seconds: 1733201265,
      nanoseconds: 362000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "cfrqrt44TVp0iZ8Ia2Zr",
    userId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
    content: "I have fluffy yarn and I can’t see the knots😭😭😭😭😭😭😭",
    tag: "mistakes",
    timestamp: {
      seconds: 1733221559,
      nanoseconds: 488000000,
    },
    clap: 122,
    clappedBy: ["aagNYe4N79XCMVaA3Vb3nmloeZh1", "IRVD2f2xkrVNoVnFKGjG7uvLwtW2"],
    replies: [
      {
        id: "rkZXo6OtBFU5rwhbEqtz",
        parentId: "cfrqrt44TVp0iZ8Ia2Zr",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "aagNYe4N79XCMVaA3Vb3nmloeZh1",
        content:
          "Fluffy yarn isn’t for beginners. You can try crocheting together with a strand of thin yarn of contrasting color",
        tag: "",
        timestamp: {
          seconds: 1733222361,
          nanoseconds: 180000000,
        },
        clap: 27,
        clappedBy: [],
        isPinned: true,
      },
    ],
  },
  {
    id: "i8q24g7MA1PDOK34Teud",
    userId: "tom_b@gmail.com",
    content: "I have a question! Did you use cotton or wool yarn?",
    tag: "questions",
    timestamp: {
      seconds: 1733201244,
      nanoseconds: 735000000,
    },
    clap: 13,
    clappedBy: [],
    replies: [
      {
        id: "G5J4W5x1HU9pNyzN3slG",
        parentId: "i8q24g7MA1PDOK34Teud",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "tom_b@gmail.com",
        content: "Thank you sm 💕",
        tag: "questions",
        timestamp: {
          seconds: 1733201245,
          nanoseconds: 496000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "vIxvcPQYeBKZVNBrdbr4",
        parentId: "i8q24g7MA1PDOK34Teud",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "tom_b@gmail.com",
        content: "milk cotton yarn!",
        tag: "questions",
        timestamp: {
          seconds: 1733201245,
          nanoseconds: 130000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "mK69G4QKDy8XOkay92sn",
    userId: "phil_s@gmail.com",
    content: "Hi, is it good for using polyester yarn for crocheting? ty!",
    tag: "questions",
    timestamp: {
      seconds: 1733201276,
      nanoseconds: 782000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "mlxx5ss5yQBMj87xBioz",
    userId: "drew_t@gmail.com",
    content:
      "Hey! I had a question. Can we use a knitting needle instead of the hook thingy😅\nIm actually a beginner and i don't have the hook so",
    tag: "questions",
    timestamp: {
      seconds: 1733201273,
      nanoseconds: 731000000,
    },
    clap: 32,
    clappedBy: [],
    replies: [
      {
        id: "enVWiw8tTBwrQtvKGyEC",
        parentId: "mlxx5ss5yQBMj87xBioz",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "drew_t@gmail.com",
        content: " @lilthings.  oh dats fine! Thanks for clearing my doubt",
        tag: "questions",
        timestamp: {
          seconds: 1733201274,
          nanoseconds: 526000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "LxGJRMLiD54vtgPxr4DT",
        parentId: "mlxx5ss5yQBMj87xBioz",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "drew_t@gmail.com",
        content:
          "knitting and crocheting is completely two different art💗 so no u could only use hook for crocheting",
        tag: "questions",
        timestamp: {
          seconds: 1733201274,
          nanoseconds: 129000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "oLCtOtiC0cAl2PU0DU9a",
    userId: "lea_p@gmail.com",
    content:
      "Is it only my yarn or why does this get mixed up all the time? What i mean is the yarn kind of splits and then i get stuck and stuff?",
    tag: "questions",
    timestamp: {
      seconds: 1733201285,
      nanoseconds: 407000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "pk7DOAfgIPx0khvEt665",
    userId: "alex42@gmail.com",
    content:
      "I was using 8 ply wool and plastic crochet hooks, however, I found it really difficult to see the v’s is it easier with 5ply wool to see the v’s? And should I invest in a non plastic crochet hook similar to yours? Thank you!",
    tag: "questions",
    timestamp: {
      seconds: 1733201237,
      nanoseconds: 31000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "rRilILzE6cciTGC9QbX4",
    userId: "mona_t@gmail.com",
    content:
      "What code is the green 5 strand milk thread you used.? is it light green or sage green.?\nThank you.",
    tag: "questions",
    timestamp: {
      seconds: 1733201292,
      nanoseconds: 238000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "sQoyEQZ8pcbFwaPnHW0C",
    userId: "zoe_m@gmail.com",
    content:
      "do you have a link to the color yarn you used? i’m trying to look on amazon for a similar color but they are all not what i’m looking for, i like the color that you used!😅",
    tag: "questions",
    timestamp: {
      seconds: 1733201241,
      nanoseconds: 290000000,
    },
    clap: 13,
    clappedBy: [],
    replies: [
      {
        id: "m6AT14CASPjkNizF1Kmc",
        parentId: "sQoyEQZ8pcbFwaPnHW0C",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "zoe_m@gmail.com",
        content:
          "no need to apologize!! thank you for responding, this tutorial was so helpful 💕",
        tag: "questions",
        timestamp: {
          seconds: 1733201242,
          nanoseconds: 46000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "g5C2ZEqp87w0kuqRsFJw",
        parentId: "sQoyEQZ8pcbFwaPnHW0C",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "zoe_m@gmail.com",
        content:
          "im soo sorry i didnt buy my yarns on anazon😭 i got it from a random store in hong kong🥹🥹",
        tag: "questions",
        timestamp: {
          seconds: 1733201241,
          nanoseconds: 677000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
  {
    id: "uVinW0vVewQ6G3lViXWq",
    userId: "wade_k@gmail.com",
    content: "What is the needle number?",
    tag: "questions",
    timestamp: {
      seconds: 1733201292,
      nanoseconds: 735000000,
    },
    clap: 3,
    clappedBy: [],
    replies: [],
  },
  {
    id: "vF7hQd9zUbKHWyakwYrh",
    userId: "theo_m@gmail.com",
    content: "what kind of yarn did you use?",
    tag: "questions",
    timestamp: {
      seconds: 1733201293,
      nanoseconds: 618000000,
    },
    clap: 14,
    clappedBy: [],
    replies: [
      {
        id: "nsVclsxfe2ek4PsfpcgV",
        parentId: "vF7hQd9zUbKHWyakwYrh",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "theo_m@gmail.com",
        content: "milk cotton",
        tag: "questions",
        timestamp: {
          seconds: 1733201294,
          nanoseconds: 363000000,
        },
        clap: 3,
        clappedBy: [],
      },
      {
        id: "f8Tahaj1Io3XTAUYdZ4K",
        parentId: "vF7hQd9zUbKHWyakwYrh",
        userId: "IRVD2f2xkrVNoVnFKGjG7uvLwtW2",
        parentUserId: "theo_m@gmail.com",
        content: "milk cottkn",
        tag: "questions",
        timestamp: {
          seconds: 1733201293,
          nanoseconds: 982000000,
        },
        clap: 3,
        clappedBy: [],
      },
    ],
  },
];
